export const skils = [
    "Next.js",
    "React.js",
    "ASP.NET",
    "Express.js",
    "TypeScript",
    "JavaScript",
    "C#",
    "MySQL",
    "SQL Server",
    "Supabase",
    "Tailwind CSS",
    "State Management",
    "REST API Development",
    "AI Integration",
    "Payment Gateway Integration",
    "WhatsApp Automation",
    "SEO Optimization",
    "Keyword Research",
    "Content Management",
    "Google Analytics",
    "Git & GitHub",
]