export const skils = [
    "TypeScript",
    "JavaScript",
    "Node.js",
    "React.js", 
    "Next.js",
    "Express.js",
    "Nest.js",
    "Redux",
    "C#",
    "ASP.NET",
    "MySQL",
    "SQL Server", 
    "MongoDB",
    "Prisma",
    "Git",
    "REST API",
    "JWT",
    "HTML",
    "CSS",
    "TailwindCSS",
    "PHP",
    "Debugging",
    "Team Collaboration",
    "SEO",
    "Copywriting",
]